<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EPRUSARW1779" failures="1" tests="4" name="Actions demo" time="25.835" errors="0" timestamp="23 Dec 2019 13:32:58 GMT">
  <testcase classname="ActionsDemoTests" name="brokenTest" time="5.629">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ActionsDemoTests.brokenTest(ActionsDemoTests.java:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- brokenTest -->
  <testcase classname="ActionsDemoTests" name="dragNDropDemo" time="3.745"/>
  <testcase classname="ActionsDemoTests" name="resizeDemo" time="3.361"/>
  <testcase classname="ActionsDemoTests" name="selectingDemo" time="2.568"/>
</testsuite> <!-- Actions demo -->
